# Importando o pacote pandas

In [1]:
import pandas as pd

#  Lendo os arquivos CSV com o pandas

In [2]:
vendas_df = pd.read_csv('Contoso-Vendas-2017.csv', sep = ';')
produtos_df = pd.read_csv('Contoso - Cadastro Produtos.csv', sep = ';')
lojas_df = pd.read_csv('Contoso - Lojas.csv', sep =';')
clientes_df = pd.read_csv('Contoso - Clientes.csv', sep = ';')
produtos_df

,Nome da Marca,Tipo,Custo Unitario,Preco Unitario,ID Produto,Categoria
0,Contoso,Econômico,"10,69","20,96",873,Acessório para Computador
1,Contoso,Econômico,"6,63",13,879,Acessório para Computador
2,Contoso,Econômico,"6,63",13,880,Acessório para Computador
3,Contoso,Econômico,"6,63",13,881,Acessório para Computador
4,Contoso,Econômico,"6,63",13,882,Acessório para Computador
...,...,...,...,...,...,...
1685,Southridge Video,Regular,"82,77","179,99",1602,Filme DVD
1686,Southridge Video,Regular,"73,57","159,99",1606,Filme DVD
1687,Southridge Video,Regular,"82,77","179,99",1607,Filme DVD
1688,Southridge Video,Regular,"73,57","159,99",1611,Filme DVD
1689,Southridge Video,Regular,"82,77","179,99",1612,Filme DVD

# Convertendo uma coluna de object para datetime

In [3]:
vendas_df['Data da Venda'] = pd.to_datetime(vendas_df['Data da Venda'], format='%d/%m/%Y')
vendas_df['Data do Envio'] = pd.to_datetime(vendas_df['Data do Envio'], format='%d/%m/%Y')

vendas_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 980642 entries, 0 to 980641
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Numero da Venda       980642 non-null  int64
 1   Data da Venda         980642 non-null  datetime64[ns]
 2   Data do Envio         980642 non-null  datetime64[ns]
 3   ID Canal              980642 non-null  int64
 4   ID Loja               980642 non-null  int64
 5   ID Produto            980642 non-null  int64
 6   ID Promocao           980642 non-null  int64
 7   ID Cliente            980642 non-null  int64
 8   Quantidade Vendida    980642 non-null  int64
 9   Quantidade Devolvida  980642 non-null  int64
dtypes: datetime64[ns](2), int64(8)
memory usage: 74.8 MB

#  Alterando ó preço do produto com ID 873 para 23 reais

In [4]:
produtos_df.loc[produtos_df["ID Produto"] == 873, "Preco Unitario"] = 23.00
produtos_df

,Nome da Marca,Tipo,Custo Unitario,Preco Unitario,ID Produto,Categoria
0,Contoso,Econômico,"10,69",23.0,873,Acessório para Computador
1,Contoso,Econômico,"6,63",13,879,Acessório para Computador
2,Contoso,Econômico,"6,63",13,880,Acessório para Computador
3,Contoso,Econômico,"6,63",13,881,Acessório para Computador
4,Contoso,Econômico,"6,63",13,882,Acessório para Computador
...,...,...,...,...,...,...
1685,Southridge Video,Regular,"82,77","179,99",1602,Filme DVD
1686,Southridge Video,Regular,"73,57","159,99",1606,Filme DVD
1687,Southridge Video,Regular,"82,77","179,99",1607,Filme DVD
1688,Southridge Video,Regular,"73,57","159,99",1611,Filme DVD
1689,Southridge Video,Regular,"82,77","179,99",1612,Filme DVD

#  Atualizando e exportando o arquivo csv

In [5]:
produtos_df.to_csv('Novo Produtosss.csv', sep = ';')